all:stack.cpp queue.cpp priority_queue.cpp bitset.cpp
	g++ stack.cpp -o stack -std=c++11
	g++ queue.cpp -o queue -std=c++11
	g++ priority_queue.cpp -o priority_queue -std=c++11
	g++ bitset.cpp -o bitset -std=c++11
.PHONY:clean
clean:
	-rm stack stack.cpp~ Makefile~ queue queue.cpp~ priority_queue priority_queue.cpp~ bitset bitset.cpp~
