all:io_function.cpp  manipulator.cpp fileIO.cpp stringIO.cpp
	g++ io_function.cpp -o io_function -std=c++11
	g++ manipulator.cpp -o manipulator -std=c++11
	g++ fileIO.cpp -o fileIO -std=c++11
	g++ stringIO.cpp -o stringIO -std=c++11
.PHONY:clean
clean:
	-rm io_function manipulator fileIO stringIO stringIO.cpp~
