all: copy.cpp move.cpp transform_Combination.cpp swap.cpp assign_value.cpp replace.cpp
	g++ copy.cpp -o copy -std=c++11
	g++ move.cpp -o move -std=c++11
	g++ transform_Combination.cpp -o transform_combine -std=c++11
	g++ swap.cpp -o swap -std=c++11
	g++ assign_value.cpp -o assign -std=c++11
	g++ replace.cpp -o replace -std=c++11
.PHONY:clean
clean:
	-rm Makefile~ copy.cpp~ copy move move.cpp~ transform_Combination.cpp~ transform_combine swap swap.cpp~ assign_value.cpp~ assign replace replace.cpp~
