all:sort.cpp heap.cpp search.cpp merge.cpp
	g++ sort.cpp -o sort -std=c++11
	g++ heap.cpp -o heap -std=c++11
	g++ search.cpp -o search -std=c++11
	g++ merge.cpp -o merge -std=c++11
.PHONY:clean
clean:
	-rm sort.cpp~ sort Makefile~ heap.cpp~ search.cpp~ search heap merge.cpp~ merge
