all:randomNumber.cpp complex.cpp globalFunction.cpp
	g++ randomNumber.cpp -o randomNumber -std=c++11
	g++ complex.cpp -o complex -std=c++11
	g++ globalFunction.cpp -o globalFunction -std=c++11
.PHONY:clean
clean:
	-rm randomNumber.cpp~ randomNumber Makefile~ complex complex.cpp~ globalFunction globalFunction.cpp~
