exe:for_each.cpp count.cpp min_max.cpp find.cpp
	g++ -o for_each for_each.cpp  -std=c++11
	g++ -o count count.cpp -std=c++11
	g++ -o min_max min_max.cpp -std=c++11
	g++ -o find find.cpp -std=c++11
.PHONY:clean
clean:
	-rm for_each  Makefile~ for_each.cpp~ count count.cpp~ min_max.cpp~
