all:numeric_limit.cpp type_utility.cpp ratio.cpp chrono.cpp
	g++ numeric_limit.cpp -o numeric_limits -std=c++11
	g++ type_utility.cpp -o type_utility -std=c++11
	g++ ratio.cpp -o ratio -std=c++11
	g++ chrono.cpp -o chrono -std=c++11
.PHONY:clean
clean:
	-rm numeric_limits numeric_limit.cpp~ Makefile~ type_utility type_utility.cpp~ ratio.cpp~ ratio chrono.cpp~ chrono

